generate_pipeline:
  stage: .pre
  script: |
    nix shell nixpkgs#yj -c bash -c <<GITLAB
    yj -yj < .ci.yaml > .ci.json
    nix eval -f .ci.nix --json "" > pipeline.yaml
    GITLAB
  artifacts:
    paths:
    - pipeline.yaml

run_pipeline:
  stage: build
  needs:
  - generate_pipeline
  trigger:
    include:
    - artifact: pipeline.yaml
      job: generate_pipeline
    strategy: depend