generate_pipeline:
  stage: .pre
  script: |
    nix eval -f .gitlab-ci.nix --json "" | \
      nix shell nixpkgs#yj -c yj -jy > pipeline.yaml
  artifacts:
    paths:
    - pipeline.yaml

run_pipeline:
  stage: build
  needs:
  - setup
  trigger:
    include:
    - artifact: pipeline.yaml
      job: setup
    strategy: depend