setup:
  stage: .pre
  script: |
    nix eval -f pipeline.nix --json "" | nix shell nixpkgs#yj -c yj -jy > pipeline.yaml
  artifacts:
    paths:
    - pipeline.yaml

run:
  stage: build
  needs:
  - setup
  trigger:
    include:
    - artifact: pipeline.yaml
      job: setup
    strategy: depend