setup:
  stage: .pre
  script: |
    nix eval -f pipeline.nix --json "" > pipeline.json
  artifacts:
    paths:
    - pipeline.json

run:
  stage: build
  needs:
  - setup
  trigger:
    include:
    - artifact: pipeline.json
      job: setup
    strategy: depend